name: release-please

on:
  push:
    branches: ["main"]

permissions: {} # Top-level permissions can often be left empty or set to read-all if job-level permissions are used

jobs:
  label-published:
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Create published label
        run: |
          gh label create 'hoge' --color=EDEDED || true

  release-please:
    if: github.repository_owner == 'Mogyuchi'
    permissions:
      contents: write      # Needed for creating releases, tags, and updating manifest/config files
      pull-requests: write # Needed for creating/updating release PRs
      issues: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release-please
        with:
          config-file: .release-please/release-please-config.json
          manifest-file: .release-please/.release-please-manifest.json
          skip-github-pull-request: ${{ startsWith(github.event.head_commit.message, 'release:') && github.event.head_commit.author.name == 'github-actions[bot]' }}
  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
    steps:
      - run: echo "hoge"
